### ISSUE TITLE
How to decrypt the bin file

### ISSUE THREAD

**Issue by xiu920411** [Razmoth/GenshinStudio#10]
Tools are useful, but bin is still ciphertext

**Comment by Razmoth** [comment]
Greetings.

Bin files, aka `MiHoYoBinData` files, seems to be serialized configs using a custom format for the client usage, as far as `GenshinStudio` is concerned, it only enables you to extract the raw data.

Beyond that, you will need to attempt to de-serialize it by reverse engineering the game binaries, good luck with that.
