### ISSUE TITLE
MSB6006 & LNK1104 while build

### ISSUE THREAD

**Issue by PackmanDude** [Razmoth/GenshinStudio#12]
![зображення](https://user-images.githubusercontent.com/99031872/170039061-14133662-f847-413a-a4d9-1e8a84ad7bd2.png)

Using VS2022 with all suggested dependencies from it. Tried literally everything to fix that. Maybe, that matter, but I installed FBX SDK from here to build it:
https://github.com/metarutaiga/FBXSDK/tree/master/include

And included folder and 1 file from it:
- fbxsdk.h
- fbxsdk/

And placed it in 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt', this is my default CRT dir, by the way

**Comment by Razmoth** [comment]
Greetings.

To build `GenshinStudio`, you'll need to install [FBX SDK 2020.2.1](https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_win.exe) on default installation location.

Then right-click on `AssetStudioFBXNative`, select properties and add the paths from screenshots.

`C/C++ -> AdditionalIncludeDirectories`
![image](https://user-images.githubusercontent.com/32140579/170650004-adb8490c-2d07-448e-ba43-604afa655110.png)

`Linker -> AdditionalLibraryDirectories`
![image](https://user-images.githubusercontent.com/32140579/170650090-a27225b2-bed5-457f-b905-ca651390b069.png)

Then it should work.
