### ISSUE TITLE
How is the asset file structure of Genshin?

### ISSUE THREAD

**Issue by sovzzz** [Razmoth/GenshinStudio#17]
It's not the problem of the Studio application, but of mine. I cannot find the asset I want. For Example, the strings of gacha titles, texture of characters' models. I don't know where did MHY place them. As a result, Icame here and beg for help.

**Comment by Razmoth** [comment]
Greetings,

These information are stored into asset_index, which has been recovered +99% by the huge efforts of Radioegor146, you can read through it and find out where exactly are assets stored (link)[https://github.com/radioegor146/gi-asset-indexes/].

To find assets first look for the desired version, open it up, then:
```
1- Search for "ART/Char/Avatar/Avatar_{Boy/Girl}_{Weapon}_{CharacterName}/Avatar_{Boy/Girl}_{Weapon}_{CharacterName}".
2- copy bundle id and search by it.
3- done (id is blk id).
```
![image](https://user-images.githubusercontent.com/32140579/171342517-112a6133-3c2c-4e27-bc17-38f50cba6b8e.png)
![image1](https://user-images.githubusercontent.com/32140579/171342514-19cee231-9304-4a22-93c9-64b283a6d672.png)

Hope that helps, no need to beg it's alright you could just ask and I'll try to help if I can.

**Comment by sovzzz** [comment]
Does the "blk id" mean .blk files' name?

**Comment by sovzzz** [comment]
> Greetings,
> 
> These information are stored into `asset_index`, which has been recovered +99% by the huge efforts of `Radioegor146`, you can read through it and find out where exactly are assets stored [link](https://github.com/radioegor146/gi-asset-indexes).
> 
> To find assets first look for the desired version, open it up, then:
> 
> ```
> 1- Search for "ART/Char/Avatar/Avatar_{Boy/Girl}_{Weapon}_{CharacterName}/Avatar_{Boy/Girl}_{Weapon}_{CharacterName}".
> 2- copy bundle id and search by it.
> 3- done (id is blk id).
> ```
> 
> ![image](https://user-images.githubusercontent.com/32140579/171342517-112a6133-3c2c-4e27-bc17-38f50cba6b8e.png) ![image1](https://user-images.githubusercontent.com/32140579/171342514-19cee231-9304-4a22-93c9-64b283a6d672.png)
> 
> Hope that helps, no need to beg it's alright you could just ask and I'll try to help if I can.

Does blk id mean .blk files' filename ? I didn't find a file like "8260369.blk"(the id from the picture). Or just beacuse MHY changed the id when update 2.6 to 2.7?
