### ISSUE TITLE
Can not export fbx with skinned mesh

### ISSUE THREAD

**Issue by WideFrost** [Razmoth/GenshinStudio#24]
version: GenshinStudio v0.16.55 (net6.0-windows)
game version: 2.8

I'm trying to export a character model to fbx, but I only got the fbx with a bunch of empties. No skinned mesh, no armature.

For example I wanted to export Qiqi, there are what I have done:
1. Go to `Misc.`->`Build BLKMap`, build the `BLKMap.bin` file.
2. Go to `Options`->`Specify AI version`, specify the AI version: `2.6.54-beta`.
3. In the `GenshinImpact_2.6.54_beta.zip_31049740.blk.asset_index.json`, I find out that `ART/Char/Avatar/Avatar_Loli_Sword_Qiqi/Avatar_Loli_Sword_Qiqi` is in the `13418737.blk` file.
4. Go to `File`->`Load file`, load the `13418737.blk` file.
5. The program automatically resolve dependancies and load more .blk files.
6. In the Scene Hierachy, I select `Avatar_Loli_Sword_Qiqi`, and go to `Model`->`Export selected objects (merge)`.
![select](https://user-images.githubusercontent.com/110982664/183910197-c1c14df4-f1d3-4ee6-abae-46ff28ca46b7.png)
7. then I got this:
![empty](https://user-images.githubusercontent.com/110982664/183911045-d3bc7bc4-228a-4fd8-a5c8-12c3394f2ab5.png)
this is my export options:
![export options](https://user-images.githubusercontent.com/110982664/183911774-febb7939-a703-4edf-ba3f-6df791c763d8.png)

Did I do something wrong?
In the `Asset list` tab, I can see Qiqi's meshes, but I can not export them as skinned mesh. Export Mesh assets in the `Asset list` tab will only give me .obj files.

**Comment by Razmoth** [comment]
Greetings,

It's probably because `Disabled Renderers` is enabled, with it all `Mesh/MeshRenderer/SkinnedMeshRenderer` will be forcefully avoided (in case a new changes happened and you still need to use it for `Texture2D/Sprite/etc`).

Let me know if that help.

**Comment by WideFrost** [comment]
Thank you so much! It works!
Unchecking `Disabled Renderers` before loading file solves this issue.
