### ISSUE TITLE
abnormally terminates when exporting FBX containing anim

### ISSUE THREAD

**Issue by RabberDakk** [Razmoth/GenshinStudio#3]
GenshinStudio abnormally terminates when exporting FBX containing animationclip. The steps to cause the issue are described below. same error occurred in the procedure using other CAB or Animator.

1. Create a CAB / CAB Map of version 2.5 blocks
2. Load `00/00536693/CAB-0b17098d4bcf8466e9170081e87f2e56`
3. Check `NPC_Avatar_Girl*` in the Scene Hierarchy Tab
4. Move Asset List Tab and select an any AnimationClip
5. `Model > Export selected objects (split) + selected AnimationClips`
6. IndexOutOfRangeException

Error at https://github.com/Razmoth/GenshinStudio/blob/master/AssetStudioUtility/ModelConverter.cs#L958-L988
```csharp
                        track.Translations.Add(new ImportedKeyframe<Vector3>(time, new Vector3
                        (
                            -data[curveIndex++ + offset],
                            data[curveIndex++ + offset],
                            data[curveIndex++ + offset]
                        )));
                        break;
                    case 2:
                        var value = Fbx.QuaternionToEuler(new Quaternion
                        (
                            data[curveIndex++ + offset],
                            -data[curveIndex++ + offset],
                            -data[curveIndex++ + offset],
                            data[curveIndex++ + offset]
                        ));
                        track.Rotations.Add(new ImportedKeyframe<Vector3>(time, value));
                        break;
                    case 3:
                        track.Scalings.Add(new ImportedKeyframe<Vector3>(time, new Vector3
                        (
                            data[curveIndex++ + offset],
                            data[curveIndex++ + offset],
                            data[curveIndex++ + offset]
                        )));
                        break;
                    case 4:
                        track.Rotations.Add(new ImportedKeyframe<Vector3>(time, new Vector3
                        (
                            data[curveIndex++ + offset],
                            -data[curveIndex++ + offset],
                            -data[curveIndex++ + offset]
                        )));
```

GenshinStudio version: 4287127dff11a2a75f51c2e376880e24683ee397
.NET version: net472
AssetIndex version: 2.5

----

I have not yet found a case where an export FBX with anim can be succeeded. I have tried with CBT2 / 2.0 / 2.4 / 2.5 blocks. `07138280.blk` that you previously told me about does not exist in these versions and I could not try it.

**Comment by Razmoth** [comment]
Greetings,

The main reason behind this issue is that Genshin Impact uses `ACLClips`, aka `Animation Compression Library` (modified version of ![acl](https://github.com/nfrechette/acl)) to compress parts of the `AnimationClip`.

So on extraction, the total clips count does not match the parsed clips (as `ACLClip `are not supported yet), and so it throws a `IndexOutOfRangeException`.

I haven't gotten around `ACLClips` as of yet, will need to read more about it sometime.

Thanks for the feedback

**Comment by RabberDakk** [comment]
Oh, makes sense. These data was missing because of the compression. Thank you very much for the detailed explanation on the specification.

> I haven't gotten around ACLClips as of yet, will need to read more about it sometime.

So excited! This tool is very interesting. If you guys start GitHub Sponsors, I'll gladly sign up right away.

**Comment by RabberDakk** [comment]
@Razmoth I met a true genius! I just tried the new release right away, so impressed with the animations are working!
I have one question. In the future, do you plan to support the output of body animations (neck, hand, spine, leg, etc.)?

----
The following is just a curiosity question of mine, so please feel free to ignore it.

When I extract an AnimationClip in the current GenshinStduio, the body animation is missing (hair, cloths, etc. are no problem). Is this because the AnimationType is Humanoid and [AssetStduio does not support Humanoid](https://github.com/Perfare/AssetStudio/issues/221)?

I looked through some AnimationClips and found that the genericBindings contains `ClassIDType.Animator`. I think this is the Bone path abstracted by Humanoid Avator, which is the reason why the body animation is missing? Currently I expect only Generic Animation to be output since it is filtered by `ClassIDType.Transform`.

```csharp
var bindingList = m_ClipBindingConstant.genericBindings.Where(x => x.typeID == ClassIDType.Transform).ToArray();
```

However, even if this expectation is correct, it seems that the number of `m_ACLClip.m_CurveCount` is not enough to create an animation for the Humanoid part 🤔 Am I right in thinking ....?
